apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "locust.fullname" . }}-master
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "locust.fullname" . }}-master
  minReplicas: {{ .Values.master.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.master.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.master.autoscaling.targetCPUUtilizationPercentage }}
